/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.UIManager;

/**
 *
 * @author Gabriel
 */
public class VistaTablero extends javax.swing.JFrame {

   ///////atributos/////////////////////
    public JButton[][] matrizVista; //matriz de botones
    
 
////////Constructor////////////////    
    public VistaTablero() {
        try{
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        }
        catch(Exception e){
            e.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(null);
        crearEscenario();
        //this.setPreferredSize(new Dimension(800,700));
    }
     public JButton[][] getCoordenadas() {
        return matrizVista;
    }
     

    public void setCoordenadas(JButton[][] coordenadas) {
        this.matrizVista = coordenadas;
    }
    
    public JButton [][] crearEscenario(){
       jPanel1.setLayout(new GridLayout(25,25)); //se le da forma de matriz al panel 
       jPanel1.setPreferredSize(new Dimension(600, 600));
        matrizVista = new JButton[25][25]; //se crea un arreglo de arreglo de botones de 25x25
        for(int i = 0; i<25;i++){
            for(int j = 0; j<25; j++){
                matrizVista[i][j] = new JButton(); //Se instancian coordenadas
                matrizVista[i][j].setMargin(new Insets(2, 2, 2, 2));
                jPanel1.add(matrizVista[i][j]);
                //Se agregan botones al panel
                matrizVista[i][j].setPreferredSize(new Dimension(25, 25));
                
                //matrizVista[i][j].setBorder(null);
                //matrizVista[i][j].setOpaque(true);
                //matrizVista[i][j].setBorderPainted(false);
            }
        }
    return matrizVista;
    }
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegresarVT = new javax.swing.JButton();
        btnAtacar = new javax.swing.JButton();
        btnMover = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();
        btnVerificarTerminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 700));
        setResizable(false);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        btnRegresarVT.setText("Regresar");
        btnRegresarVT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAtacar.setText("Atacar");
        btnAtacar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnMover.setText("Mover");
        btnMover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnTerminar.setText("Terminar Turno");
        btnTerminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnVerificarTerminar.setText("Aceptar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegresarVT)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(btnAtacar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(btnMover, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(btnVerificarTerminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnTerminar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnRegresarVT)
                .addGap(225, 225, 225)
                .addComponent(btnAtacar)
                .addGap(53, 53, 53)
                .addComponent(btnMover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTerminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerificarTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnTerminar, btnVerificarTerminar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtacar;
    private javax.swing.JButton btnMover;
    private javax.swing.JButton btnRegresarVT;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JButton btnVerificarTerminar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void agregarListener(ActionListener al){ //metodo que escucha botones
        
        btnRegresarVT.addActionListener(al);
        btnMover.addActionListener(al);
        btnAtacar.addActionListener(al);
        btnTerminar.addActionListener(al);
        btnVerificarTerminar.addActionListener(al);
        
        
        
        for(int i= 0; i<25; i++){
            for(int j= 0; j<25;j++){
                matrizVista[i][j].setFocusPainted(true);
                matrizVista[i][j].addActionListener(al);
                //escucha a todos los botones de la matriz
                matrizVista[i][j].setOpaque(true);

            }
        }
    }
    
    
    
    public void agregarMouseListener(MouseListener m){ //metodo que escucha botones
        
       
        
        
        for(int i= 0; i<25; i++){
            for(int j= 0; j<25;j++){
                
                matrizVista[i][j].addMouseListener(m);
                
                

            }
        }
    }
    
    public JButton getBtnVerificarTerminar(){
        return this.btnVerificarTerminar;
    }

    public JButton getBtnRegresarVT() {
        return this.btnRegresarVT;
    }

    public JButton[][] getMatrizVista() {
        return this.matrizVista;
    }

    public JButton getBtnAtacar() {
        return this.btnAtacar;
    }

    public JButton getBtnMover() {
        return this.btnMover;
    }

    public JButton getBtnTerminar() {
        return this.btnTerminar;
    }
   
    

    
  
    
    
    
    
    
}














