/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Gabriel
 */
public class VistaRamosCivil extends javax.swing.JFrame {

    /**
     * Creates new form VistaRamos
     */
    public VistaRamosCivil() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCalculoI = new javax.swing.JButton();
        btnMetodosDeProgramacion = new javax.swing.JButton();
        btnFundaEconomia = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnCalculoI.setText("CALCULO I");
        btnCalculoI.setMaximumSize(new java.awt.Dimension(50, 23));
        btnCalculoI.setMinimumSize(new java.awt.Dimension(50, 23));
        btnCalculoI.setPreferredSize(null);
        getContentPane().add(btnCalculoI);
        btnCalculoI.setBounds(0, 90, 100, 41);

        btnMetodosDeProgramacion.setFont(new java.awt.Font("Lucida Grande", 0, 9)); // NOI18N
        btnMetodosDeProgramacion.setText("<html><center>METODOS <br><center>DE <br><center>PROGRAMACIÓN");
        btnMetodosDeProgramacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodosDeProgramacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnMetodosDeProgramacion);
        btnMetodosDeProgramacion.setBounds(200, 290, 100, 41);

        btnFundaEconomia.setFont(new java.awt.Font("Lucida Grande", 0, 9)); // NOI18N
        btnFundaEconomia.setText("<html><center>FUNDAMENTOS<br><center> DE LA<br><center> ECONOMIA");
        btnFundaEconomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFundaEconomiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnFundaEconomia);
        btnFundaEconomia.setBounds(200, 250, 100, 41);

        jButton4.setText("FISICA I");
        jButton4.setPreferredSize(null);
        getContentPane().add(jButton4);
        jButton4.setBounds(0, 170, 100, 41);

        jButton5.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        jButton5.setText("<html><center>INTRODUCCION <br><center> A LA <br><center>INGENIERIA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(0, 210, 100, 40);

        jButton6.setFont(new java.awt.Font("Lucida Grande", 0, 6)); // NOI18N
        jButton6.setText("<html><center>TALLER DE DESARROLLO <center>PERSONAL E INTEGRAL");
        getContentPane().add(jButton6);
        jButton6.setBounds(0, 250, 100, 40);

        jButton7.setFont(new java.awt.Font("Lucida Grande", 0, 9)); // NOI18N
        jButton7.setText("<html><center>METODOS <br><center>DE <br><center>ESTUDIO");
        getContentPane().add(jButton7);
        jButton7.setBounds(0, 290, 100, 41);

        jButton8.setText("CALCULO II");
        getContentPane().add(jButton8);
        jButton8.setBounds(100, 90, 100, 41);

        jButton9.setText("ALGEBRA II");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(100, 130, 100, 41);

        jButton10.setText("FISICA II");
        getContentPane().add(jButton10);
        jButton10.setBounds(100, 170, 101, 41);

        jButton11.setText("QUÍMICA");
        getContentPane().add(jButton11);
        jButton11.setBounds(100, 210, 101, 40);

        jButton12.setFont(new java.awt.Font("Lucida Grande", 0, 5)); // NOI18N
        jButton12.setText("<html><center>FUNDAMENTOS DE LA <br><center>COMPUTACIÓN Y LA <br><center>PROGRAMACIÓN");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(100, 250, 100, 41);

        jButton13.setText("jButton13");
        jButton13.setPreferredSize(null);
        getContentPane().add(jButton13);
        jButton13.setBounds(600, 290, 100, 41);

        jButton14.setFont(new java.awt.Font("Lucida Grande", 0, 9)); // NOI18N
        jButton14.setText("<html><center>COMUNICACION<br><center> EFECTIVA");
        getContentPane().add(jButton14);
        jButton14.setBounds(200, 130, 100, 41);

        jButton15.setText("INGLES I");
        getContentPane().add(jButton15);
        jButton15.setBounds(200, 170, 100, 41);

        jButton16.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jButton16.setText("<html><center>ECUACIONES <br><center>DIFERENCIALES");
        getContentPane().add(jButton16);
        jButton16.setBounds(200, 210, 100, 40);

        jButton17.setText("ELECTRICIDAD Y MAGENTISMO");
        getContentPane().add(jButton17);
        jButton17.setBounds(200, 90, 100, 41);

        jButton18.setText("ALGEBRA I");
        getContentPane().add(jButton18);
        jButton18.setBounds(0, 130, 100, 41);

        jButton19.setText("CALCULO III");
        getContentPane().add(jButton19);
        jButton19.setBounds(300, 90, 100, 41);

        jButton20.setText("INGLES II");
        getContentPane().add(jButton20);
        jButton20.setBounds(300, 130, 100, 41);

        jButton21.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jButton21.setText("<html><center>ANALISIS <br><center>ESTADISTICO");
        getContentPane().add(jButton21);
        jButton21.setBounds(300, 170, 100, 41);

        jButton22.setFont(new java.awt.Font("Lucida Grande", 0, 9)); // NOI18N
        jButton22.setText("<html><center>ESTRUCTURA <br><center>DE <br><center>COMPUTADORES");
        getContentPane().add(jButton22);
        jButton22.setBounds(300, 210, 100, 40);

        jButton23.setFont(new java.awt.Font("Lucida Grande", 0, 9)); // NOI18N
        jButton23.setText("<html><center>PARADIGMAS<br><center>DE<br><center>PROGRAMACIÓN");
        getContentPane().add(jButton23);
        jButton23.setBounds(300, 250, 100, 41);

        jButton24.setFont(new java.awt.Font("Lucida Grande", 0, 7)); // NOI18N
        jButton24.setText("<html><center>ANALISIS DE DATOS Y <br><center>ESTRUCTURA DE DATOS");
        getContentPane().add(jButton24);
        jButton24.setBounds(300, 290, 100, 41);

        jButton25.setText("jButton25");
        jButton25.setPreferredSize(null);
        getContentPane().add(jButton25);
        jButton25.setBounds(400, 90, 100, 41);

        jButton26.setText("jButton26");
        jButton26.setPreferredSize(null);
        getContentPane().add(jButton26);
        jButton26.setBounds(400, 130, 100, 41);

        jButton27.setText("jButton27");
        jButton27.setPreferredSize(null);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton27);
        jButton27.setBounds(400, 170, 100, 41);

        jButton28.setText("jButton28");
        jButton28.setPreferredSize(null);
        getContentPane().add(jButton28);
        jButton28.setBounds(400, 210, 100, 40);

        jButton29.setText("jButton29");
        jButton29.setPreferredSize(null);
        getContentPane().add(jButton29);
        jButton29.setBounds(400, 250, 100, 41);

        jButton30.setText("jButton30");
        jButton30.setPreferredSize(null);
        getContentPane().add(jButton30);
        jButton30.setBounds(400, 290, 100, 41);

        jButton31.setText("jButton31");
        jButton31.setPreferredSize(null);
        getContentPane().add(jButton31);
        jButton31.setBounds(500, 90, 100, 41);

        jButton32.setText("jButton32");
        jButton32.setPreferredSize(null);
        getContentPane().add(jButton32);
        jButton32.setBounds(500, 130, 100, 41);

        jButton33.setText("jButton33");
        jButton33.setPreferredSize(null);
        getContentPane().add(jButton33);
        jButton33.setBounds(500, 170, 100, 41);

        jButton34.setText("jButton34");
        jButton34.setPreferredSize(null);
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton34);
        jButton34.setBounds(500, 210, 100, 40);

        jButton35.setText("jButton35");
        jButton35.setPreferredSize(null);
        getContentPane().add(jButton35);
        jButton35.setBounds(500, 250, 100, 41);

        jButton36.setText("jButton36");
        jButton36.setPreferredSize(null);
        getContentPane().add(jButton36);
        jButton36.setBounds(500, 290, 100, 41);

        jButton37.setText("jButton37");
        jButton37.setPreferredSize(null);
        getContentPane().add(jButton37);
        jButton37.setBounds(600, 90, 100, 41);

        jButton38.setText("jButton38");
        jButton38.setPreferredSize(null);
        getContentPane().add(jButton38);
        jButton38.setBounds(600, 130, 100, 41);

        jButton39.setText("jButton39");
        jButton39.setPreferredSize(null);
        getContentPane().add(jButton39);
        jButton39.setBounds(600, 170, 100, 41);

        jButton40.setText("jButton40");
        jButton40.setPreferredSize(null);
        getContentPane().add(jButton40);
        jButton40.setBounds(600, 210, 100, 40);

        jButton41.setText("jButton41");
        getContentPane().add(jButton41);
        jButton41.setBounds(600, 250, 100, 41);

        jButton42.setText("jButton42");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton42);
        jButton42.setBounds(700, 90, 100, 41);

        jButton43.setText("jButton43");
        getContentPane().add(jButton43);
        jButton43.setBounds(700, 130, 100, 41);

        jButton44.setText("jButton44");
        getContentPane().add(jButton44);
        jButton44.setBounds(700, 170, 100, 41);

        jButton45.setText("jButton45");
        getContentPane().add(jButton45);
        jButton45.setBounds(700, 210, 100, 40);

        jButton46.setText("jButton46");
        getContentPane().add(jButton46);
        jButton46.setBounds(700, 250, 100, 41);

        jButton47.setText("jButton47");
        getContentPane().add(jButton47);
        jButton47.setBounds(800, 90, 100, 41);

        jButton48.setText("jButton48");
        getContentPane().add(jButton48);
        jButton48.setBounds(800, 130, 100, 41);

        jButton49.setText("jButton49");
        getContentPane().add(jButton49);
        jButton49.setBounds(800, 170, 100, 41);

        jButton50.setText("jButton50");
        getContentPane().add(jButton50);
        jButton50.setBounds(800, 210, 100, 40);

        jButton51.setText("jButton51");
        getContentPane().add(jButton51);
        jButton51.setBounds(800, 250, 100, 41);

        jButton52.setText("jButton52");
        getContentPane().add(jButton52);
        jButton52.setBounds(900, 90, 100, 41);

        jButton53.setText("jButton53");
        getContentPane().add(jButton53);
        jButton53.setBounds(900, 130, 100, 41);

        jButton54.setText("jButton54");
        getContentPane().add(jButton54);
        jButton54.setBounds(900, 170, 100, 41);

        jButton55.setText("jButton55");
        getContentPane().add(jButton55);
        jButton55.setBounds(900, 210, 100, 40);

        jButton56.setText("jButton56");
        getContentPane().add(jButton56);
        jButton56.setBounds(900, 250, 100, 41);

        jButton57.setText("jButton57");
        getContentPane().add(jButton57);
        jButton57.setBounds(1000, 90, 100, 41);

        jButton58.setText("jButton58");
        getContentPane().add(jButton58);
        jButton58.setBounds(1000, 130, 100, 41);

        jButton59.setText("jButton59");
        getContentPane().add(jButton59);
        jButton59.setBounds(1000, 170, 100, 41);

        jButton60.setText("jButton60");
        getContentPane().add(jButton60);
        jButton60.setBounds(1000, 210, 100, 40);

        jButton61.setText("jButton61");
        getContentPane().add(jButton61);
        jButton61.setBounds(1000, 250, 100, 41);

        jButton62.setText("jButton62");
        getContentPane().add(jButton62);
        jButton62.setBounds(1100, 90, 105, 41);

        jLabel1.setText("Semestre 5");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(410, 70, 90, 16);

        jLabel2.setText("Semestre 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 90, 16);

        jLabel3.setText("Semestre 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 70, 90, 16);

        jLabel4.setText("Semestre 3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 70, 90, 16);

        jLabel5.setText("Semestre 4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 70, 90, 16);

        jLabel6.setText("Semestre 12");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1110, 70, 90, 16);

        jLabel7.setText("Semestre 6");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(510, 70, 90, 16);

        jLabel8.setText("Semestre 7");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(610, 70, 90, 16);

        jLabel9.setText("Semestre 8");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(710, 70, 90, 16);

        jLabel10.setText("Semestre 9");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(810, 70, 90, 16);

        jLabel11.setText("Semestre 10");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(910, 70, 90, 16);

        jLabel12.setText("Semestre 11");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1010, 70, 90, 16);

        filler1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(filler1);
        filler1.setBounds(100, 90, 0, 250);

        filler2.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(filler2);
        filler2.setBounds(200, 60, 0, 300);

        filler3.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(filler3);
        filler3.setBounds(300, 60, 0, 300);

        filler4.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(filler4);
        filler4.setBounds(400, 60, 0, 300);

        filler5.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(filler5);
        filler5.setBounds(500, 60, 0, 300);

        filler6.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(filler6);
        filler6.setBounds(500, 60, 0, 300);

        filler7.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(filler7);
        filler7.setBounds(600, 70, 0, 300);

        filler8.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(filler8);
        filler8.setBounds(700, 70, 0, 300);

        filler9.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(filler9);
        filler9.setBounds(800, 70, 0, 300);

        filler10.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(filler10);
        filler10.setBounds(900, 60, 0, 300);

        filler11.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(filler11);
        filler11.setBounds(1000, 60, 0, 300);

        filler12.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(filler12);
        filler12.setBounds(1100, 60, 0, 300);
        getContentPane().add(filler13);
        filler13.setBounds(0, 250, 1100, 0);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel13.setText("Sexto Año");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(1050, 20, 110, 30);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel14.setText("Primer Año");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 20, 110, 30);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel15.setText("Segundo Año");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(260, 20, 110, 30);

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel16.setText("Tercer Año");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(460, 20, 110, 30);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel18.setText("Cuarto Año");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(650, 20, 110, 30);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel19.setText("Quinto Año");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(860, 20, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMetodosDeProgramacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodosDeProgramacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMetodosDeProgramacionActionPerformed

    private void btnFundaEconomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFundaEconomiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFundaEconomiaActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void mai(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRamosCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRamosCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRamosCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRamosCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRamosCivil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculoI;
    private javax.swing.JButton btnFundaEconomia;
    private javax.swing.JButton btnMetodosDeProgramacion;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    
    public void agregarListener(ActionListener al){
        this.btnCalculoI.addActionListener(al);
        this.btnMetodosDeProgramacion.addActionListener(al);
        this.btnFundaEconomia.addActionListener(al);
        
        
        
            
        
    }

    public JButton getBtnCalculoI() {
        return this.btnCalculoI;
    }

    public JButton getBtnMetodosDeProgramacion() {
        return this.btnMetodosDeProgramacion;
    }

    public JButton getBtnFundaEconomia() {
        return this.btnFundaEconomia;
    }






}
