/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.GridLayout;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author arru
 */
public class VistaBatallaCorta extends javax.swing.JFrame {
    private JButton[][] espaciosJugador;
    private JLabel[][]espaciosEnemigo;

    /**
     * Creates new form VistaBatallaCorta
     */
    public VistaBatallaCorta() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombrePersonaje = new javax.swing.JLabel();
        nombreEnemigo = new javax.swing.JLabel();
        monitoEnemigo = new javax.swing.JLabel();
        monitoPersonaje = new javax.swing.JLabel();
        panelJugador = new javax.swing.JPanel();
        panelEnemigo = new javax.swing.JPanel();
        ataqueAlto = new javax.swing.JButton();
        ataqueBajo = new javax.swing.JButton();
        ataqueMedio = new javax.swing.JButton();
        ataqueEsp = new javax.swing.JButton();
        combatir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Batalla Corta >:c");

        nombrePersonaje.setText("jLabel1");

        nombreEnemigo.setText("jLabel2");

        javax.swing.GroupLayout panelJugadorLayout = new javax.swing.GroupLayout(panelJugador);
        panelJugador.setLayout(panelJugadorLayout);
        panelJugadorLayout.setHorizontalGroup(
            panelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelJugadorLayout.setVerticalGroup(
            panelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelEnemigoLayout = new javax.swing.GroupLayout(panelEnemigo);
        panelEnemigo.setLayout(panelEnemigoLayout);
        panelEnemigoLayout.setHorizontalGroup(
            panelEnemigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );
        panelEnemigoLayout.setVerticalGroup(
            panelEnemigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        ataqueAlto.setText("Ataque Alto");

        ataqueBajo.setText("Ataque Bajo");

        ataqueMedio.setText("Ataque Medio");

        ataqueEsp.setText("Ataque Esp");

        combatir.setText("Combatir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(monitoPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 17, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ataqueBajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ataqueAlto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ataqueEsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ataqueMedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(panelJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(nombrePersonaje)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nombreEnemigo)
                        .addGap(128, 128, 128))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(combatir)
                        .addContainerGap(106, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelEnemigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(monitoEnemigo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePersonaje)
                    .addComponent(nombreEnemigo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(monitoEnemigo, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelEnemigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(monitoPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ataqueAlto)
                            .addComponent(ataqueMedio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ataqueBajo)
                            .addComponent(ataqueEsp)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(combatir)))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ataqueAlto;
    private javax.swing.JButton ataqueBajo;
    private javax.swing.JButton ataqueEsp;
    private javax.swing.JButton ataqueMedio;
    private javax.swing.JButton combatir;
    private javax.swing.JLabel monitoEnemigo;
    private javax.swing.JLabel monitoPersonaje;
    private javax.swing.JLabel nombreEnemigo;
    private javax.swing.JLabel nombrePersonaje;
    private javax.swing.JPanel panelEnemigo;
    private javax.swing.JPanel panelJugador;
    // End of variables declaration//GEN-END:variables
    public JButton[][] getEspaciosJugador(){
        return espaciosJugador;
    }
    public JLabel[][] getEspaciosEnemigo(){
        return espaciosEnemigo;
    }
    public JButton getAtaqueAlto(){
        return ataqueAlto;
    }
    public JButton getAtaqueMedio(){
        return ataqueMedio;
    }
    public JButton getAtaqueBajo(){
        return ataqueBajo;
    }
    public JButton getAtaqueEsp(){
        return ataqueEsp;
    }   
    public JButton getCombatir(){
        return combatir;
    }
    public JPanel getEspacioJugador(){
        return panelJugador;
    }
    public JPanel getEspacioEnemigo(){
        return panelEnemigo;
    }
    public JLabel getMonitoPersonaje(){
        return monitoPersonaje;
    }
    public JLabel getMonitoEnemigo(){
        return monitoEnemigo;
    }
    public JLabel getNombrePersonaje(){
        return nombrePersonaje;
    }
    public JLabel getNombreEnemigo(){
        return nombreEnemigo;
    }
    public void agregarListener(ActionListener al){
        this.ataqueAlto.addActionListener(al);
        this.ataqueMedio.addActionListener(al);
        this.ataqueBajo.addActionListener(al);
        this.ataqueEsp.addActionListener(al);
        this.combatir.addActionListener(al);
    }
    
    public void crearMonito(String ruta,JLabel jlabel){
        ImageIcon imagen = new ImageIcon(ruta);
        jlabel.setIcon(imagen);
    }   
    
    public void ponerNombre(String nombre,JLabel jlabel){
        jlabel.setText(nombre);
    }   
    public void crearEspaciosJugador(){
        espaciosJugador = new JButton[1][7];
        this.panelJugador.setLayout(new GridLayout(1,7));
        for(int j=0; j<7; j++){
            espaciosJugador[0][j] = new JButton();
            espaciosJugador[0][j].setText("");
            espaciosJugador[0][j].setEnabled(false);
            panelJugador.add(espaciosJugador[0][j]);
        }
    } 
    public void crearEspaciosEnemigo(){
        espaciosEnemigo = new JLabel[1][7];
        this.panelEnemigo.setLayout(new GridLayout(1,7));
        for(int j=0; j<7; j++){
            espaciosEnemigo [0][j] = new JLabel();
            espaciosEnemigo[0][j].setText(" ;___; ");
            panelEnemigo.add(espaciosEnemigo[0][j]);
        }
    }
    public void colocarAtaqueEnemigo(ArrayList<String> combinacion, JLabel[][] jlabel){
        for (int i=0; i<7; i++){
            String actual=combinacion.get(i);
            jlabel[0][i].setText(actual);
            panelEnemigo.add(jlabel[0][i]);
        }
        
    }    
    
}
