/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JRadioButton;

/**
 *
 * @author Gabriel
 */
public class VistaSelecPjes extends javax.swing.JFrame {

    /**
     * Creates new form VistaSelecPjes
     */
    public VistaSelecPjes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        btnUlloa = new javax.swing.JRadioButton();
        btnRusio = new javax.swing.JRadioButton();
        btnCharlie = new javax.swing.JRadioButton();
        btnArru = new javax.swing.JRadioButton();
        btnPoto = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        btnSelec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Skia", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("Selección De Personajes");

        buttonGroup1.add(btnUlloa);
        btnUlloa.setText("Ulloa Machine");
        btnUlloa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlloaActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnRusio);
        btnRusio.setText("rusio");

        buttonGroup1.add(btnCharlie);
        btnCharlie.setText("Charlie Killer 17");

        buttonGroup1.add(btnArru);
        btnArru.setText("CumbiArru");

        buttonGroup1.add(btnPoto);
        btnPoto.setText("Potokslfjksd");

        jTextField1.setText("jTextField1");

        btnSelec.setText("Seleccionar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPoto)
                            .addComponent(btnArru)
                            .addComponent(btnCharlie)
                            .addComponent(btnUlloa)
                            .addComponent(btnRusio))
                        .addGap(101, 101, 101)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnSelec)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnUlloa)
                        .addGap(18, 18, 18)
                        .addComponent(btnRusio)
                        .addGap(18, 18, 18)
                        .addComponent(btnCharlie)
                        .addGap(18, 18, 18)
                        .addComponent(btnArru)
                        .addGap(18, 18, 18)
                        .addComponent(btnPoto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addComponent(btnSelec)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUlloaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlloaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUlloaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSelecPjes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSelecPjes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSelecPjes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSelecPjes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaSelecPjes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnArru;
    private javax.swing.JRadioButton btnCharlie;
    private javax.swing.JRadioButton btnPoto;
    private javax.swing.JRadioButton btnRusio;
    private javax.swing.JButton btnSelec;
    private javax.swing.JRadioButton btnUlloa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public void AgregarActionListener(ActionListener e){
        
        this.btnSelec.addActionListener(e);
        
        
    }
    
    public JRadioButton getRadioBtnULLOA() {
        return btnUlloa;
    }

    public JRadioButton getRadioBtnRusio() {
        return btnRusio;
    }

    public JRadioButton getRadioBtnCharlie() {
        return btnCharlie;
    }

    public JRadioButton getRadioBtnArru() {
        return btnArru;
    }

    public JRadioButton getRadioBtnPoto() {
        return btnPoto;
    }

    public JButton getBtnSelec() {
        return btnSelec;
    }
    
    
    














}
