/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Gabriel
 */
public class VistaSelecPjes extends javax.swing.JFrame {

    /**
     * Creates new form VistaSelecPjes
     */
    public VistaSelecPjes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnSelec = new javax.swing.JButton();
        btnCharlie = new javax.swing.JButton();
        btnUlloa = new javax.swing.JButton();
        btnArru = new javax.swing.JButton();
        btnPoto = new javax.swing.JButton();
        btnRusio = new javax.swing.JButton();
        btnDeshacer = new javax.swing.JButton();
        btnVaciar = new javax.swing.JButton();
        btnTerminarSeleccion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Skia", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("Selección De Personajes");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 22, 378, 36);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(438, 84, 165, 227);

        btnSelec.setText("Seleccionar");
        getContentPane().add(btnSelec);
        btnSelec.setBounds(180, 345, 115, 29);

        btnCharlie.setText("Charlie Killer");
        getContentPane().add(btnCharlie);
        btnCharlie.setBounds(180, 84, 135, 29);

        btnUlloa.setText("Ulloa");
        getContentPane().add(btnUlloa);
        btnUlloa.setBounds(180, 131, 135, 29);

        btnArru.setText("Arru");
        getContentPane().add(btnArru);
        btnArru.setBounds(180, 178, 135, 29);

        btnPoto.setText("Potojsdsadasd");
        getContentPane().add(btnPoto);
        btnPoto.setBounds(180, 225, 135, 29);

        btnRusio.setText("Rusio");
        getContentPane().add(btnRusio);
        btnRusio.setBounds(180, 272, 135, 29);

        btnDeshacer.setText("Deshacer");
        getContentPane().add(btnDeshacer);
        btnDeshacer.setBounds(313, 345, 90, 29);

        btnVaciar.setText("Vaciar");
        getContentPane().add(btnVaciar);
        btnVaciar.setBounds(80, 345, 82, 29);

        btnTerminarSeleccion.setText("Terminar Seleccion");
        getContentPane().add(btnTerminarSeleccion);
        btnTerminarSeleccion.setBounds(438, 345, 165, 29);

        jLabel1.setText("Personajes Seleccionados");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 70, 170, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSelecPjes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSelecPjes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSelecPjes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSelecPjes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaSelecPjes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArru;
    private javax.swing.JButton btnCharlie;
    private javax.swing.JButton btnDeshacer;
    private javax.swing.JButton btnPoto;
    private javax.swing.JButton btnRusio;
    private javax.swing.JButton btnSelec;
    private javax.swing.JButton btnTerminarSeleccion;
    private javax.swing.JButton btnUlloa;
    private javax.swing.JButton btnVaciar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public void AgregarActionListener(ActionListener al){
        
        this.btnSelec.addActionListener(al);
        this.btnDeshacer.addActionListener(al);
        this.btnArru.addActionListener(al);
        this.btnCharlie.addActionListener(al);
        this.btnRusio.addActionListener(al);
        this.btnPoto.addActionListener(al);
        this.btnUlloa.addActionListener(al);
        this.btnVaciar.addActionListener(al);
        this.btnTerminarSeleccion.addActionListener(al);
    }
    
    public JButton getBtnULLOA() {
        return btnUlloa;
    }

    public JButton getBtnRusio() {
        return btnRusio;
    }

    public JButton getBtnCharlie() {
        return btnCharlie;
    }

    public JButton getBtnArru() {
        return btnArru;
    }

    public JButton getBtnPoto() {
        return btnPoto;
    }

    public JButton getBtnSelec() {
        return btnSelec;
    }
    
    public JButton getBtnDeshacer() {
        return btnDeshacer;
    }

    public JButton getBtnVaciar() {
        return btnVaciar;
    }

    public JButton getBtnTerminarSeleccion() {
        return btnTerminarSeleccion;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }
    
    

    
    
    
    
    














}
