/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.GridLayout;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import Controlador.ControladorAhorcado;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author arru
 */
public class VistaAhorcado extends javax.swing.JFrame {
    private JButton[][] espacios;
    private ControladorAhorcado ca;

    /**
     * Creates new form VistaAhorcado
     */
    public VistaAhorcado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField = new javax.swing.JTextField();
        espacioMonito = new javax.swing.JLabel();
        ingresarLetra = new javax.swing.JButton();
        panelVacio = new javax.swing.JPanel();
        pista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ahorcado Nyus :3");

        ingresarLetra.setBackground(new java.awt.Color(255, 255, 153));
        ingresarLetra.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        ingresarLetra.setText("Ingresar letra");
        ingresarLetra.setToolTipText("");
        ingresarLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarLetraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVacioLayout = new javax.swing.GroupLayout(panelVacio);
        panelVacio.setLayout(panelVacioLayout);
        panelVacioLayout.setHorizontalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );
        panelVacioLayout.setVerticalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pista.setForeground(new java.awt.Color(255, 153, 51));
        pista.setText("Pista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ingresarLetra)
                .addGap(55, 55, 55)
                .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(espacioMonito, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pista)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(panelVacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(espacioMonito, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(pista)))
                .addGap(18, 18, 18)
                .addComponent(panelVacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresarLetra))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarLetraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarLetraActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel espacioMonito;
    private javax.swing.JButton ingresarLetra;
    private javax.swing.JTextField jTextField;
    private javax.swing.JPanel panelVacio;
    private javax.swing.JButton pista;
    // End of variables declaration//GEN-END:variables
    //RETORNA BOTON INGRESAR LETRA.
    public JButton getButtoningresarLetra(){
        return ingresarLetra;
    }
    //AGREGA LOS LISTENER A LOS BOTONES.
    public void agregarListener(ActionListener al){
        this.ingresarLetra.addActionListener(al);
        this.pista.addActionListener(al);
    }
    //RETORNA EL TEXTO PRESENTE EN EL TEXTFIELD.
    public String getLetra(){
        return jTextField.getText();
    }
    //RETORNA EL JLABEL DONDE SE COLOCA EL AHORCADO.
    public JLabel jLabel1(){
        return espacioMonito;
    }
    //RETORNA EL ARREGLO DE BOTONES QUE REPRESENTAN LOS ESPACIOS VACIOS.
    public JButton[][] getEspacios(){
        return espacios;
    }
    //RETORNA EL PANEL DONDE SE COLOCA EL ARREGLO DE BOTONES.
    public JPanel getPanelVacio(){
        return panelVacio;
    }
    //RETORNA EL BOTON PISTA.
    public JButton getPista(){
        return pista;
    }
    //PRODUCE QUE EL TEXTFIELD ESTE VACION PARA RECIBIR UNA NUEVA LETRA.
    public void devolverBlanco(){
        this.jTextField.setText("");
    }
    //DESHABILITA EL BOTON PISTA.
    public void apagarBoton(){
        this.pista.setEnabled(false);
    }
    //GENERA EL ARREGLO DE BOTONES.
    public void crearEspacios(int a){
        espacios = new JButton[1][a];
        this.panelVacio.setLayout(new GridLayout(1,a));
        for(int j=0; j<a; j++){
            espacios [0][j] = new JButton();
            espacios[0][j].setText(";__;");
            espacios[0][j].setEnabled(false);
            panelVacio.add(espacios[0][j]);
        }
    }  
    //COLOCA EL ARREGLO DE BOTONES ACTUALIZADO EN EL PANEL.
    public void cambiarPanelVacio(JButton[][] jbutton, ArrayList<Integer> enteritos, String letra, String palabra){
        int a= palabra.length();
        for(int j=0; j<a; j++){
            panelVacio.add(jbutton[0][j]);
        }
    }    
    //COLOCA EL LA IMAGEN DEL AHORCADO EN EL JLABEL.    
    public void crearMonito(String ruta){
        ImageIcon imagen = new ImageIcon(ruta);
        espacioMonito.setIcon(imagen);
        
    }    
        
    
    
}

       
        
        
    

    
    //public void setLetra(String letra){
        //System.out.println(letra);
    

